### ISSUE TITLE
Add page for JavaChampions

### ISSUE THREAD

**Issue by hendrikebbers** [karakun/karakun.github.io#128]
See https://community.oracle.com/community/groundbreakers/java/java-champions and https://www.theserverside.com/definition/Java-Champion

**Comment by LeonSpikes** [comment]
I'll do this 👍

**Comment by giftkugel** [comment]
Should this be a list of java champions at Karakun?

> See https://community.oracle.com/community/groundbreakers/java/java-champions and https://www.theserverside.com/definition/Java-Champion

Should that page be a list of Java Champions at Karakun?
