### ISSUE TITLE
create a GDPR conform Privacy Statement and Imprint 

### ISSUE THREAD

**Issue by timo0** [karakun/karakun.github.io#13]
We have to create a Privacy Statement and Imprint for the Homepage.

Blocks #3 and #6

**Comment by hendrikebbers** [comment]
@timo0 kannst du dich darum kümmern?

**Comment by timo0** [comment]
Yep

Current and planned Services:
* GitHub Pages
* Google Fonts
* Disqus
* Piwik/Google Analytics

Google Fonts is a easy task to avoid and I would suggest to do so.
