### ISSUE TITLE
Newsletter signup form 

### ISSUE THREAD

**Issue by kress04** [karakun/karakun.github.io#132]
@timo0 : The signup form contains the section "Marketing Permissions". This is afaik related to GDPR. In this section a subscriber can define the ways he wants us to contact him. One of the fields is "Direct Mails" (by post). As we are not collecting addresses, this doesn't make sense. 

@hendrikebbers : the MailChimp account contains private information of you! For example, your private address is shown after completing the signup process:

<img width="692" alt="image" src="https://user-images.githubusercontent.com/16147401/51970686-d6810a80-2477-11e9-9443-4a7b9edd31e6.png">

Your email address is also mentioned in the double opt-in message:
<img width="693" alt="image" src="https://user-images.githubusercontent.com/16147401/51970750-f7e1f680-2477-11e9-924f-d4e2bb208ba9.png">

**Comment by hendrikebbers** [comment]
Fixed :)
<img width="734" alt="bildschirmfoto 2019-01-30 um 10 23 07" src="https://user-images.githubusercontent.com/9443847/51971290-18f71700-2479-11e9-9981-364b17ace19a.png">

<img width="695" alt="bildschirmfoto 2019-01-30 um 10 22 57" src="https://user-images.githubusercontent.com/9443847/51971308-1f858e80-2479-11e9-9b54-7f6ebbab1a99.png">

**Comment by hendrikebbers** [comment]
@timo0 pls remove direct mail. Once this is done the issue can be closed

**Comment by timo0** [comment]
ah okay our understanding was that we can send a e-mail direkt/personally

**Comment by kress04** [comment]
https://www.linguee.de/englisch-deutsch/uebersetzung/direct+mail.html ;)

**Comment by timo0** [comment]
:*
