### ISSUE TITLE
Gap inbetween border and featured images

### ISSUE THREAD

**Issue by martinfrancois** [karakun/karakun.github.io#155]
Can be seen on the landing page (https://dev.karakun.com/) as well as the talks page (https://dev.karakun.com/talks/)

Inbetween the featured images and the border there is a strange white gap, see the red marked rectangle:
![Bildschirmfoto 2020-06-03 um 11 23 14](https://user-images.githubusercontent.com/14319020/83620268-61eb3e00-a58d-11ea-891d-aeb5a800d96c.png)

**Comment by kress04** [comment]
@martinfrancois: which browser are you using? I tested the same with Safari and Firefox -  everything looks ok on my side:

<img width="687" alt="image" src="https://user-images.githubusercontent.com/16147401/83997844-a1d06d80-a95f-11ea-93c7-1aa161fcb6fa.png">

<img width="678" alt="image" src="https://user-images.githubusercontent.com/16147401/83998036-0986b880-a960-11ea-906d-640352d0e8a4.png">

Only Chrome is showing some strange behavior with the mentioned spaces around featured pics:

<img width="764" alt="image" src="https://user-images.githubusercontent.com/16147401/83998112-33d87600-a960-11ea-925d-5642bc3744a9.png">

The spaces may vary from pic to pic... @giftkugel: any ideas why Chrome does this?

**Comment by giftkugel** [comment]
It somehow depends on the zoom level in Chrome:

![image](https://user-images.githubusercontent.com/9103924/83999448-0e00a080-a963-11ea-9479-33904f61470c.png)

![image](https://user-images.githubusercontent.com/9103924/83999460-15c04500-a963-11ea-8e54-7099b46d42d3.png)

At the end it seems, that Chrome has issues with the relative border size. Maybe we can teak it a bit.
