### ISSUE TITLE
Home Layout is broken

### ISSUE THREAD

**Issue by hendrikebbers** [karakun/karakun.github.io#169]
The new reading time looks really good on the article / post page. On the home page / overview page the reading time layout is broken. I attached images how it looks on safari. Maybe we should remove it from the main page for now and only add it to the post view.

<img width="1392" alt="Bildschirmfoto 2020-12-04 um 18 47 59" src="https://user-images.githubusercontent.com/9443847/101196839-908fc180-3661-11eb-8fe6-66d42be0ac22.png">
<img width="1392" alt="Bildschirmfoto 2020-12-04 um 18 47 53" src="https://user-images.githubusercontent.com/9443847/101196855-95ed0c00-3661-11eb-9d16-9e79da191f03.png">

**Comment by sclassen** [comment]
To fix this we should re-add the reading time on the overview page
