### ISSUE TITLE
What UI Framework should we use?

### ISSUE THREAD

**Issue by hendrikebbers** [karakun/karakun.github.io#2]
Currently I really like https://bulma.io :)

**Comment by timo0** [comment]
In this discussion I have no particular opinion I challenge Markus and Simon to take this decision 👍

**Comment by giftkugel** [comment]
I am fine with every framework, I don't need a framework at all. 😄 
But I would go with https://bulma.io/ too.

It's new, it's fancy and it's not overused like Bootstrap afaik.

And @hendrikebbers is into Bulma since I tweet(ed) about it. :stuck_out_tongue:

**Comment by Dierk** [comment]
I think we should be very cautious with _every_ dependency (library or tool) that we have to maintain over a long time.

**Comment by hendrikebbers** [comment]
+1
Bulma is „only“ a basic CSS

Von meinem iPhone gesendet

**Comment by Dierk** [comment]
Hm, but it requires putting sass in the tool chain, or not?

**Comment by hendrikebbers** [comment]
No, you can add the plain CSS files. We use Jekyll to create the static sides out of metadata / markdown. Jekyll supports sass by default. Already discussed this with @giftkugel - I would only use CSS, he is pro Sass. Anyway I do not think that we will start directly with a layout that will stand for the next years. Most important point is to have a page that we can use to post news, articles, talks...

Von meinem iPhone gesendet

**Comment by hendrikebbers** [comment]
So I‘m fine with both as long as we have a first good looking page as soon as possible :)

Von meinem iPhone gesendet

**Comment by giftkugel** [comment]
I prefer SASS, because it is already in the Jekyll + Github Pages tool chain. We can take advantage of it without effort.
