### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by hendrikebbers** [karakun/karakun.github.io#21]
We need some text and a header image for the about page

**Comment by hendrikebbers** [comment]
We should start to discuss in this issue what should be shown on the about page

**Comment by madmas** [comment]
PR was merged despite its WIP state - so I reopen this issue to keep track of the open points:

TODO:

 * [ ] Add links for all unsplash images (@hendrikebbers)
 * [ ] add nice paragraph about the developer hub
 * [ ] add link / credits for the logo designer

**Comment by giftkugel** [comment]
Changed with #50
