### ISSUE TITLE
We need a domain

### ISSUE THREAD

**Issue by hendrikebbers** [karakun/karakun.github.io#23]
Since Google still do not provide the .dev domains we should start with another domain that will redirect to the final .dev domain once it is available. Maybe we can create a subdomain like developer.karakun.com.
@martin-huber is this possible?
@timo0 @madmas @giftkugel what do you think?

**Comment by timo0** [comment]
+1 for the sub domain.. for me we should also have a separate mail account as well

**Comment by madmas** [comment]
subdomain seems to be fine, but developer is looong ;) 
dev.karakun.com ? or 
hub.karakun.com ? or 
devhub.karakun.com ?

**Comment by sclassen** [comment]
dev.karakun.com !!
