### ISSUE TITLE
Better layout for header images

### ISSUE THREAD

**Issue by hendrikebbers** [karakun/karakun.github.io#24]
In the user section the header images often do not look that good. Here we need to be more flexible.

**Comment by giftkugel** [comment]
What's the user section?

**Comment by hendrikebbers** [comment]
Example: https://karakun.github.io/people/mittie.html

**Comment by giftkugel** [comment]
You can set the `background-position-y` to bottom for mittie.

You can also try another value: [https://developer.mozilla.org/en-US/docs/Web/CSS/background-position-y](https://developer.mozilla.org/en-US/docs/Web/CSS/background-position-y)

**Comment by hendrikebbers** [comment]
ok and what is the 2nd property that I can use?

**Comment by giftkugel** [comment]
Currently we support `background-position-y`, `background-position-x`, `background-size` for the _hero header_ image.

[https://developer.mozilla.org/de/docs/Web/CSS/background-size](https://developer.mozilla.org/de/docs/Web/CSS/background-size)

Take a look in `header.html`

**Comment by hendrikebbers** [comment]
THX :) Will play with the parameters
