### ISSUE TITLE
Headlines have different colors

### ISSUE THREAD

**Issue by hendrikebbers** [karakun/karakun.github.io#25]
Different layers of headlines (h1-h5) sometimes have different colors. Have a look at this article:
https://karakun.github.io/2018/06/25/java-releases.html

"Do I need to pay for Java now?" AGAINST "The Java release train"

**Comment by giftkugel** [comment]
Thats because one headline is the main one, the others are part of the content.
That's a Bulma default. We haven't changed the colors of the headlines on our own.

**Comment by hendrikebbers** [comment]
We got a color palette from the designer
![karakun_colors](https://user-images.githubusercontent.com/9443847/43035444-1885816a-8cf0-11e8-9e44-94cad76d1e38.jpg)
