### ISSUE TITLE
What tool should we use for comments?

### ISSUE THREAD

**Issue by hendrikebbers** [karakun/karakun.github.io#3]
DISQUS ?

**Comment by giftkugel** [comment]
Which comments?
For users visiting karakun.github.io?
I don't know any tool besides Disqus.

**Comment by hendrikebbers** [comment]
Yes, for comments on blog posts. I don’t know any other tool, too. That’s why I’m asked ;)

**Comment by timo0** [comment]
Since we have to respect the new EU privacy policy we should wait until we see that DiSQUS is compliant to the new regulations

**Comment by hendrikebbers** [comment]
guck mal @timo0

https://www.ithelps.at/datenschutzerklaerung
Wenn wir das reinnehmen sollte es doch alles passen, oder?

**Comment by hendrikebbers** [comment]
https://www.ithelps.at/blog/99-online-marketing/762-kontaktformulare-dsgvo

**Comment by hendrikebbers** [comment]
https://blog.disqus.com/update-on-privacy-and-gdpr-compliance

**Comment by timo0** [comment]
Is this so important? I’ve serious concerns because of the GDPR

**Comment by hendrikebbers** [comment]
From my part of view comments are an important tool for blogs. You get feedback, can start discussions... As far I understand we can use Disqus when we add the right paragraphs to the privacy statement?

**Comment by VincentTam** [comment]
> Which comments?
> For users visiting karakun.github.io?
> I don't know any tool besides Disqus.

There're plenty of them.  You may see https://github.com/Pelican-Elegant/elegant/issues/288 for a discussion about migrating from Disqus.
