### ISSUE TITLE
Listings are missing linebreaks

### ISSUE THREAD

**Issue by madmas** [karakun/karakun.github.io#32]
Introduces the latest UI changes, the listings don't reflect the linebreak from the sources anymore: 
<img width="926" alt="bildschirmfoto 2018-07-02 um 15 12 30" src="https://user-images.githubusercontent.com/37251/42166196-869015b6-7e0a-11e8-9645-bb89c74422ab.png">

@giftkugel Have you already noticed? :)

**Comment by giftkugel** [comment]
Fixed with commit 8f54757a29c018cf26d0fdd343d0ed953d55892e
I've also added `overflow`, so it's possible to scroll inside the listing.
