### ISSUE TITLE
statistics tool

### ISSUE THREAD

**Issue by hendrikebbers** [karakun/karakun.github.io#6]
We need some tools to track statistics (visits, etc.)
Any idea what we can use here?

**Comment by ribeaud** [comment]
If so, then you have to be aware of **GDPR** (http://www.dmnews.com/retail-week/gdpr-cookies-personal-data/article/738977/)

**Comment by hendrikebbers** [comment]
@timo0 but we should have it from the start ;)

**Comment by timo0** [comment]
Sure no veto but we also start not tomorrow so we have some time to take this decision

**Comment by timo0** [comment]
@martin-huber did we have already a running matomo?

**Comment by sclassen** [comment]
do we have tracking on our main site?

**Comment by hendrikebbers** [comment]
I do not thinks so. Maybe the default Wordpress tracking.

**Comment by madmas** [comment]
yes, we use google analytics there. I'd vote to host a matomo for ourself. it's really easy :)

**Comment by sclassen** [comment]
does anyone know how much we pay for a vm with our IaaS provider?

**Comment by sclassen** [comment]
@jporzelt Can you give some insight on how we could host mamoto (needs PHP & MySQL)

**Comment by jporzelt** [comment]
Would be possible to have a separate instance for it or host it together with our public website. I'll clarify with Martin...

**Comment by jporzelt** [comment]
matomo is now live in our intranet. I'll check next week why it's not reachable from outside
