### ISSUE TITLE
Adding some info for mittie

### ISSUE THREAD

**Issue by hendrikebbers** [karakun/karakun.github.io#9]
hi,
can you please add a bio to https://github.com/karakun/karakun.github.io/blob/master/_people/mittie.md
Based on your book and the talk in Bucharest your profile is already linked on 2 pages ;)

You can have a look at https://github.com/karakun/karakun.github.io/blob/master/_people/hendrik.md

**Comment by hendrikebbers** [comment]
@Dierk PING :)

**Comment by Dierk** [comment]
done. Please let me know if it needs to be more extensive.
